package pos.project_d;

import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.Point;
import javax.swing.JPanel;
import pos.project_d.panel.LoginPanel;
import pos.project_d.utils.SessionManager;
/**
 * Dashboard JFrame - Main UI after login
 */
public class Dashboard extends javax.swing.JFrame {
    private pos.project_d.panel.TitleBar titleBar; // ✅ Declare TitleBar
    private JPanel centerPanel;

    public Dashboard() {
        
        SessionManager.getAccountData();
        initComponents();
        
        setLayout(null);
        titleBar = new pos.project_d.panel.TitleBar();
        titleBar.setBounds(0, 0, getWidth(), 50);
        add(titleBar);
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        setLocationRelativeTo(null);
        
        
        add(Menu);
        Menu.setBounds(0, 0, 193, getHeight()); // ✅ Overlay Menu over TitleBar
        add(invoicePanel);
        
        this.Menu.setVisible(false);
        this.invoicePanel.setVisible(false); 
        setLocationRelativeTo(null);

        LoginPanel loginPanel = new LoginPanel(this);
        centerPanel = new JPanel();
        centerPanel.setLayout(new GridBagLayout());
        centerPanel.add(loginPanel);

        setLayout(new BorderLayout());
        add(centerPanel, BorderLayout.CENTER);
        centerPanel.setVisible(true);
    }
    
    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {
    Point p = evt.getLocationOnScreen();
    this.setLocation(p);
}


    public void showMainContent() {
        centerPanel.setVisible(false);
        Menu.setVisible(true);
        invoicePanel.setVisible(true);
        
        revalidate(); 
        repaint(); 
    }
    
    public void showLoginScreen() {
        
        Menu.setVisible(false);
        invoicePanel.setVisible(false);
        centerPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Menu = new pos.project_d.panel.Menu();
        invoicePanel = new pos.project_d.panel.InvoicePanel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 576));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 399, Short.MAX_VALUE)
                .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(invoicePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pos.project_d.panel.Menu Menu;
    private pos.project_d.panel.InvoicePanel invoicePanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
