/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.project_d.panel;

import javax.swing.JButton;

/**
 *
 * @author Nathan
 */
public class MenuItems extends javax.swing.JPanel {

    /**
     * Creates new form SidePanelContent
     */
    public MenuItems() {
        initComponents();
        setupMenuButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     private void setupMenuButtons() {
        // Create buttons
        JButton homeButton = new JButton("Home");
        JButton deliveryButton = new JButton("Delivery");
        JButton salesButton = new JButton("Sales");
        JButton adminButton = new JButton("Admin");

        // Set layout
        javax.swing.GroupLayout layout = (javax.swing.GroupLayout) this.getLayout();
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        // Horizontal group
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton)
            .addComponent(deliveryButton)
            .addComponent(salesButton)
            .addComponent(adminButton)
        );

        // Vertical group
        layout.setVerticalGroup(
            layout.createSequentialGroup()
            .addComponent(homeButton)
            .addComponent(deliveryButton)
            .addComponent(salesButton)
            .addComponent(adminButton)
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
