package pos.project_d.panel;

import javax.swing.*;
import java.awt.*;

/**
 * MenuItems - Transparent buttons with only text visible.
 */
public class MenuItems extends JPanel {
    private final JButton[] buttons; // ✅ Store buttons in an array

    public MenuItems() {
        setOpaque(false);
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS)); // ✅ Keeps vertical alignment

        buttons = new JButton[]{
            createButton("Home"),
            createButton("Delivery"),
            createButton("Sales"),
            createButton("Admin")
        };

        for (JButton button : buttons) {
            add(button);
        }
    }

    private JButton createButton(String text) {
        JButton button = new JButton(text);
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setForeground(Color.WHITE);
        button.setAlignmentX(Component.LEFT_ALIGNMENT);
        return button;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
