package pos.project_d.panel;

import javax.swing.JOptionPane;
import pos.project_d.Dashboard;
import pos.project_d.utils.SessionManager;

/**
 * Menu Panel - Contains navigation and logout functionality
 */
public class Menu extends javax.swing.JPanel {
        public Menu() { // ✅ No longer requires Dashboard
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuItems1 = new pos.project_d.panel.MenuItems();
        LogoutLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(68, 92, 156));
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Dacillo Waters");

        LogoutLabel.setBackground(new java.awt.Color(204, 204, 204));
        LogoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutLabel.setForeground(new java.awt.Color(204, 204, 204));
        LogoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLabel.setText("Logout");
        LogoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LogoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menuItems1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuItems1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(LogoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutAction(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutAction
    int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to log out?", "Confirm Logout", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            SessionManager.logout(); // ✅ Clears session
            getTopLevelAncestor().setVisible(false); // ✅ Close current window (Dashboard)

            // ✅ Reopen Dashboard with login screen
            java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JLabel jLabel1;
    private pos.project_d.panel.MenuItems menuItems1;
    // End of variables declaration//GEN-END:variables
}
